# Generated by Django 2.1.5 on 2019-01-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=300)),
                ('status', models.CharField(choices=[('u', 'Unchecked'), ('c', 'Checked')], default='u', max_length=1)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(blank=True)),
                ('ref', models.CharField(default='', max_length=500)),
                ('question', models.CharField(default='', max_length=100)),
                ('options', models.CharField(default='', max_length=500)),
                ('vote_counts', models.CharField(default='0', max_length=500)),
                ('type', models.CharField(choices=[('o', 'One of many'), ('s', 'Several of many'), ('d', 'discrete')], default='o', max_length=1)),
                ('closing_time', models.DateTimeField(blank=True)),
                ('edited', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkedvoting',
            name='voting_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vote.VoteModel'),
        ),
    ]
