# Generated by Django 2.1.4 on 2019-01-20 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 11, 26, 21, 644968)),
        ),
    ]
