# Generated by Django 2.1.3 on 2019-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='options',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vote',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
