# Generated by Django 2.1.5 on 2019-01-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190122_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='closing_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
