# Generated by Django 2.1.3 on 2019-01-06 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190104_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular voting', primary_key=True, serialize=False),
        ),
    ]
