# Generated by Django 2.1.3 on 2019-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190119_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
