# Generated by Django 2.1.3 on 2019-01-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190106_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='name',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='text',
        ),
    ]
