# Generated by Django 2.1.3 on 2019-01-06 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20190106_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular voting', primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=100)),
                ('options', models.CharField(default='', max_length=500)),
                ('type', models.CharField(choices=[('o', 'One of many'), ('s', 'Several of many'), ('d', 'discrete')], default='o', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
