# Generated by Django 2.1.3 on 2019-01-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20190107_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votemodel',
            old_name='questions',
            new_name='question',
        ),
    ]
