# Generated by Django 2.1.3 on 2019-01-11 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='closing_poll_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 12, 18, 46, 19, 13756)),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
