# Generated by Django 2.1.5 on 2019-01-11 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0008_reportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedVotings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 16, 53, 18, 229750)),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='ref',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='checkedvotings',
            name='voting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteModel'),
        ),
    ]
