# Generated by Django 2.1.5 on 2019-01-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20190111_1653'),
        ('vote', '0010_reportmodel_author'),
    ]

    operations = [
    ]
