# Generated by Django 2.1.3 on 2019-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20190115_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='closing_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
