# Generated by Django 2.1.5 on 2019-01-11 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_merge_20190111_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='creator',
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 22, 49, 57, 939399)),
        ),
    ]
