# Generated by Django 2.1.3 on 2019-01-13 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20190111_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedvotings',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkedvotings',
            name='voting_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vote.VoteModel'),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 35, 6, 931338)),
        ),
    ]
