# Generated by Django 2.1.3 on 2019-01-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20190112_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='vote_counts',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 15, 20, 41, 567893)),
        ),
    ]
