# Generated by Django 2.1.3 on 2019-01-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20190113_1635'),
        ('vote', '0014_auto_20190112_1520'),
    ]

    operations = [
    ]
