# Generated by Django 2.1.3 on 2019-01-13 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_auto_20190113_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 21, 10, 10, 172321)),
        ),
    ]
